### ISSUE TITLE
'Download All'

### ISSUE THREAD

**Issue by Ganticdotco** [rnarrkus/sketchsheets#6]
I can imagine many of us would love a 'Download All' button somewhere on that site ;)

Awesome resource though – haven't needed to use them yet, but I'll keep the link handy for when I do!

**Comment by rnarrkus** [comment]
I plan on adding  a download all button and I'm experimenting with a select all by device button. Thanks :)

**Comment by jeremybeasley** [comment]
:+1: I was just going to add this myself after manually selecting 71 items.
